name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: List Schemes
        run: xcodebuild -list

      - name: Build iOS App
        run: |
          xcodebuild \
          -project TestChatApp.xcodeproj \
          -scheme TestChatApp \
          -sdk iphonesimulator \
          -configuration Debug \
          build
