name: iOS Build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Go to Project Folder
        run: cd TestChatApp

      - name: List Files
        run: ls -la TestChatApp

      - name: List Schemes
        run: |
          cd TestChatApp
          xcodebuild -list

      - name: Build App
        run: |
          cd TestChatApp
          xcodebuild \
          -project TestChatApp.xcodeproj \
          -scheme TestChatApp \
          -sdk iphonesimulator \
          -configuration Debug \
          build
